### ISSUE TITLE
Module not found: Error: Can't resolve '@apocentre/alias-sampling'

### ISSUE THREAD

**Issue by diliburong** [ngraveio/bc-ur#21]
hi,our project build failed, I think it was caused by this change. You updated the dependencies of packge.json, but did not update the imports in the file

https://github.com/ngraveio/bc-ur/commit/c600f86c9e776d4ef601c378413aa9175bf46205

**Comment by Charon-Fan** [comment]
You can now try version 1.1.9; the https://github.com/ngraveio/bc-ur/pull/20 has been merged.

**Comment by mcintyre94** [comment]
@Charon-Fan unfortunately this doesn't seem to have fixed the issue. I have a stackblitz repro that just tried to call `UR.fromBuffer` (copied from the readme): https://stackblitz.com/edit/node-gccshg?file=index.mjs

If you open that you'll see when it runs there's an error:

```sh
❯ npm install && node index.mjs

added 1 package, removed 1 package, and changed 1 package in 1s

23 packages are looking for funding
  run `npm fund` for details
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/home/projects/node-gccshg/node_modules/@ngraveio/bc-ur/' imported from /home/projects/node-gccshg/index.mjs
    at __node_internal_ (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:36:5406)
    at new <anonymous> (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:36:4168)
    at legacyMainResolve (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:114:3751)
    at packageResolve (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:114:9538)
    at https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:114:11305
    at defaultResolve (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:114:12167)
    at nextResolve (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:248:2120)
    at ESMLoader.resolve (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:248:7556)
    at ESMLoader.getModuleJob (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:248:4387)
    at https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:181:932
    at _0x15be0c.link (https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:352:381954)
    at https://nodegccshg-hzv5.w-credentialless-staticblitz.com/blitz.c9a8a620.js:181:893 {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

If you go to package.json and change the version to 1.1.6 `"@ngraveio/bc-ur": "1.1.9"`

And run `npm install && node index.mjs` again, you'll see it succeeds:

```sh
npm install && node index.mjs

added 1 package, removed 1 package, and changed 1 package in 1s

23 packages are looking for funding
  run `npm fund` for details
done!
```

Stackblitz link for 1.1.6: https://stackblitz.com/edit/node-hvrtw3?file=package.json

**Comment by Charon-Fan** [comment]
Hi @mcintyre94 , thank you very much for providing the reproduction steps. In the 0.1.2 version of @keystonehq/alias-sampling, we now provide exports for both cjs and mjs modules to fix some compatibility issues. Additionally, I checked the npm code for version 1.1.9 of @ngraveio/bc-ur, available at https://www.npmjs.com/package/@ngraveio/bc-ur?activeTab=code, and it seems that the packaging step was overlooked before publishing. Perhaps this information can help the repository maintainers to address the issue promptly. @xardass

**Comment by xardass** [comment]
Hi @mcintyre94 please try v1.1.12

**Comment by mcintyre94** [comment]
Sorry, forgot to reply here - 1.1.12 is good, thankyou!
